### PR TITLE
Dont allow dupe SIDs on a system

### PR DESCRIPTION
**Pull request by iphands**

### CODE REVIEW

**Comment by iphands** [comment]
I think this is safe to merge thoughts?

**Comment by iphands** [comment]
@SteveHNH Can you ack/nack

**Comment by SteveHNH** [comment]
@iphands @CodeHeeler Does this one mean that we just drop dupes, or do we reject it if it comes through with more than one of the same SID? I want to prune it on the puptoo side if this schema will reject any payloads with dupes.

**Comment by CodeHeeler** [comment]
> @iphands @CodeHeeler Does this one mean that we just drop dupes, or do we reject it if it comes through with more than one of the same SID? I want to prune it on the puptoo side if this schema will reject any payloads with dupes.

I'm guessing it's rejected in which case yes, you doing something to the puptoo side is a great idea.

**Comment by SteveHNH** [comment]
@CodeHeeler Okay. I'll make a ticket for me to ensure that all the ones we send are unique as well

**Review by SteveHNH — APPROVED** [review]
approved! Need to make a change in puptoo as well, but this looks good to me.

**Comment by jharting** [comment]
Do we know if there are any conflicting entries (i.e. hosts with duplicate values) stored in inventory currently?

**Comment by SteveHNH** [comment]
@CodeHeeler good news, everyone. We're already using a set comprehension for SAP sids. No changes necessary in puptoo

**Comment by iphands** [comment]
> Do we know if there are any conflicting entries (i.e. hosts with duplicate values) stored in inventory currently?
@jharting There are tons due to QE I think.

@kruai @gmcculloug Can we run the numbers?
And include in the details which account numbers have dupes?
I want to pick out the QE and 540155 account.

**Comment by SteveHNH** [comment]
Since we've been doing SAP SIDs as sets for a while, we shouldn't have any. Unless a different reporter has been throwing them in there.

**Comment by tahmidefaz** [comment]
New Report:
```
{
  "ingress": {
    "pass_count": 0,
    "fail_count": 0
  },
  "puptoo": {
    "pass_count": 520788,
    "fail_count": 0
  },
  "rhsm-conduit": {
    "pass_count": 287657,
    "fail_count": 0
  },
  "yupana": {
    "pass_count": 228362,
    "fail_count": 0
  }
}
```
Looks good, should we merge it?

**Comment by kruai** [comment]
@tahmidefaz can you share the script you ran the query data against? Just wanna make sure those numbers make sense. A little surprised to see 0 failures

**Comment by tahmidefaz** [comment]
@kruai Yes! Here it is! https://gist.github.com/tahmidefaz/19b24056f009ac6e94e3a2f9e43aa435

**Comment by kruai** [comment]
Great! That script looks like it should work.

**Review by kruai — APPROVED** [review]
LGTM!

**Comment by kruai** [comment]
@tahmidefaz I'm going to merge this PR, but can you please make the corresponding update in HBI (or just let me know if it's already been made)? Thanks!

**Comment by tahmidefaz** [comment]
@kruai I don't think there is one, I will make a corresponding on in HBI v. soon :+1:

**Pull request merged**
