### PR TITLE
Include all remaining packages not in installed_packages

### PR DESCRIPTION
**Pull request by CodeHeeler**
A way to have all packages passed along and not only the max of multi values provided by installed_packages without breaking those dependent on the current implementation of installed_packages.

Dependent on:
https://github.com/RedHatInsights/insights-puptoo/pull/69

### CODE REVIEW

**Review by kruai — COMMENTED** [review]
This looks fine to me, though I wonder if we could define a regex "pattern" for both this field and installed_packages... Even something really loose like ^.+:.+$, just to make sure it's using the right format. That makes the assumption that all packages follow the format shown in the "example" field, though

**Comment by CodeHeeler** [comment]
> This looks fine to me, though I wonder if we could define a regex "pattern" for both this field and installed_packages... Even something really loose like ^.+:.+$, just to make sure it's using the right format. That makes the assumption that all packages follow the format shown in the "example" field, though

Created an issue to track this works separately as we'll want to be careful with changes effecting installed_packages.
https://issues.redhat.com/browse/HBISPSC-27

Let's leave this PR as is. Thanks for the suggestion though!

**Comment by kruai** [comment]
Thanks for creating a ticket to track that! I think this PR is fine, then.

**Review by kruai — APPROVED** [review]

**Comment by CodeHeeler** [comment]
Updated name to installed_packages_delta as per today's discussion.

**Comment by gmcculloug** [comment]
@iphands Can you take a quick look?  Should be ready to merge.

**Review by kruai — APPROVED** [review]

**Review by ryandillinfelton — APPROVED** [review]

**Review by thearifismail — APPROVED** [review]

**Review by ryandillinfelton — APPROVED** [review]

**Pull request merged**
