### PR TITLE
Add system_purpose fields

### PR DESCRIPTION
**Pull request by kruai**
Addresses this implementation Jira: https://issues.redhat.com/browse/ESSNTL-600
Parent Jira: https://issues.redhat.com/browse/ESSNTL-578

### CODE REVIEW

**Review by gmcculloug — APPROVED** [review]
Based on the field values defined in [Chapter 12. Configuring System Purpose](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/configuring-system-purpose-advanced_installing-rhel-as-an-experienced-user) this looks good to me.  👍

**Comment by kruai** [comment]
@SteveHNH Is this addition OK with you?

**Review by CodeHeeler — APPROVED** [review]

**Comment by SteveHNH** [comment]
@kruai Looks good to me!

**Comment by SteveHNH** [comment]
the close and comment button are too close together >_>

**Comment by kruai** [comment]
@SteveHNH can you please approve the PR? It will remain blocked until you leave an actual review :)

**Review by ryandillinfelton — APPROVED** [review]

**Pull request merged**
