### PR TITLE
Use x-propertyNames in place of propertyNames

### PR DESCRIPTION
**Pull request by tahmidefaz**
OpenApi specification does not support `propertyNames`. Check [here](https://swagger.io/docs/specification/data-models/keywords/).
We will use a custom validator to treat `x-propertyNames` as `propertyNames`.

HBI PR that handles `x-propertyNames`: https://github.com/RedHatInsights/insights-host-inventory/pull/771

### CODE REVIEW

**Comment by gmcculloug** [comment]
@tahmidefaz If there is a PR for handling `x-propertyNames` it would be nice to include a link to that PR in the description so a reviewer can easily validate and help understand the dependency between the two PRs.

**Comment by tahmidefaz** [comment]
@gmcculloug Good idea! Just added it! :+1:

**Review by kruai — APPROVED** [review]
LGTM, but we should wait until https://github.com/RedHatInsights/insights-host-inventory/pull/771 is merged first, right?

**Comment by tahmidefaz** [comment]
Either way should be fine. But, we can wait for the HBI PR  :+1:

**Comment by kruai** [comment]
Oh that's right, we still make changes in 2 places. In that case, we don't need to hold :)

**Review by ryandillinfelton — APPROVED** [review]
Looks good :+1:

**Pull request merged**
