### PR TITLE
Remove the RPMOSTreeDeployment origin minLength restriction

### PR DESCRIPTION
**Pull request by JoySnow**
Resolve inventory-schema validation issue in [RHINENG-8752](https://issues.redhat.com/browse/RHINENG-8752)

### CODE REVIEW

**Review by thearifismail — APPROVED** [review]
LGTM.  I tested by creating hosts using the following `rpm_ostree_deployments` with `origin: ""` and `origin: ""shmorigin` and hosts were created successfully.  
```
        "rpm_ostree_deployments": [{  # origin empty
            "id": "fedora-silverblue-63335a77f9853618ba1a5f139c5805e82176a2a040ef5e34d7402e12263af5bb.0",
            "checksum": "63335a77f9853618ba1a5f139c5805e82176a2a040ef5e34d7402e12263af5bb",
            "origin": "",
            "osname": "fedora-silverblue",
            "version": "33.21",
            "booted": True,
            "pinned": False,
        }]
```

**Comment by thearifismail** [comment]
@csams are you okay with removing `minimum length` requirement for `rpm_ostree_deployments.origin`?  I see you had added `rpm_ostree_deployments` to the System Profile Schema and need to make sure that it does not pose any problems for the services which needed `rpm_ostree_*` in hosts' system_profile.

**Review by thearifismail — COMMENTED** [review]
@JoySnow, I rescinding my approval of this PR. The reason is that this change may affect "edge" systems.  That's said, "puptoo" may be updated to deal with "empty" strings for "origin". 
There is a need for further discussion to be had as to how "bifrost" can affect "edge" systems.

**Comment by xiangce** [comment]
According to the discussion on the Jira ticket, we can go ahead and merge this PR, regarding the identification of "bifrost" system, a new Jira ticket will be opened.

**Review by kruai — APPROVED** [review]

**Pull request merged**
