### PR TITLE
RHINENG-2402 add failed services for systemd

### PR DESCRIPTION
**Pull request by r14chandra**
[RHINENG-2402](https://issues.redhat.com/browse/RHINENG-2402)

### CODE REVIEW

**Comment by strider** [comment]
Hi @r14chandra,

You can safely ignore the validations linting issue, which is not related to your changes. FYI, I am trying to fix it with #116.

**Review by strider — APPROVED** [review]

**Comment by kruai** [comment]
@r14chandra With the addition of this field, do we still need `failed`, the field directly above this one?

**Comment by r14chandra** [comment]
> @r14chandra With the addition of this field, do we still need `failed`, the field directly above this one?

@kruai Yes we require that as well because `failed` will just show the total no. of failed units.

**Comment by kruai** [comment]
> > @r14chandra With the addition of this field, do we still need `failed`, the field directly above this one?
> 
> @kruai Yes we require that as well because `failed` will just show the total no. of failed units.

I figured, but it seems redundant since you'll also have an array of all the services, which you could just get the length/size of

**Comment by r14chandra** [comment]
> > > @r14chandra With the addition of this field, do we still need `failed`, the field directly above this one?
> > 
> > 
> > @kruai Yes we require that as well because `failed` will just show the total no. of failed units.
> 
> I figured, but it seems redundant since you'll also have an array of all the services, which you could just get the length/size of

Yes, correct. But I don't know if the team requesting this feature would want to discard the use of `failed`.

**Review by kruai — APPROVED** [review]

**Pull request merged**
