### PR TITLE
Downgrade schema from draft 7 to draft 4

### PR DESCRIPTION
**Pull request by tahmidefaz**
Trying to use a Draft 7 validator to validate system_profile in HBI is causing us some hurdles as I explained [here](https://github.com/RedHatInsights/insights-host-inventory/pull/771#issuecomment-756366770).
I found the draft 7 version of the schema that lives in this repo to be fully backward compatible with draft 4, and I don't think we will be needing those draft 7 features of the schema here (feel free to disagree). While trying to resolve the discrepancies, we found it to be simpler to use a draft 4 validator instead of a draft 7 one. Therefore, I am opening this PR to downgrade this to draft 4 for the sake of consistency. 

Links:

- [HBI PR](https://github.com/RedHatInsights/insights-host-inventory/pull/771)
- [Draft 4 -> Draft 6 changes](https://json-schema.org/draft-06/json-schema-release-notes.html)
- [Draft 6 -> Draft 7 changes](https://json-schema.org/draft-07/json-schema-release-notes.html)

### CODE REVIEW

**Comment by kruai** [comment]
@tahmidefaz [RHCLOUD-10815](https://issues.redhat.com/browse/RHCLOUD-10815) and [RHCLOUD-8639](https://issues.redhat.com/browse/RHCLOUD-8639) say that we need to use at least Draft 6 to use propertyNames, which is needed to validate the DiskDevice object's properties. Wouldn't downgrading to Draft 4 break this?

**Comment by tahmidefaz** [comment]
> @tahmidefaz [RHCLOUD-10815](https://issues.redhat.com/browse/RHCLOUD-10815) and [RHCLOUD-8639](https://issues.redhat.com/browse/RHCLOUD-8639) say that we need to use at least Draft 6 to use propertyNames, which is needed to validate the DiskDevice object's properties. Wouldn't downgrading to Draft 4 break this?

You are right. Great catch! Initially when I looked at the validation functions for connexion's version of jsonschema validation, I misread one of the names for `propertyNames`. I double-checked and found that `propertyNames` isn't there. Closing this. :roll_eyes:

**Comment by tahmidefaz** [comment]
Reopening this as we are now considering this schema a draft 4 with added enhancements like `x-propertyNames` internally.
See RedHatInsights/insights-host-inventory#771

**Review by thearifismail — APPROVED** [review]
LGTM

**Review by kruai — APPROVED** [review]

**Pull request merged**
